version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: monthly
    groups:
      npm-dependencies:
        patterns: ["*"]

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    groups:
      pip-dependencies:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: terraform
    directory: /infra
    schedule:
      interval: monthly
