steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'functions'
  - 'deploy'
  - 'portfolio-contact-2'
  - '--trigger-topic=portfolio-contact-emails'
  - '--runtime=python39'
  - '--entry-point=send_email'
  - '--region=us-central1'
  - '--source=backend/app/utils'
  - '--env-vars-file=.env.yaml'

substitutions:
  _SMTP_SERVER: smtp.gmail.com
  _SMTP_PORT: '587'
  _SMTP_USERNAME: jckail13@gmail.com

availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/smtp-password/versions/latest
    env: 'SMTP_PASSWORD'

options:
  logging: CLOUD_LOGGING_ONLY

artifacts:
  objects:
    location: 'gs://${PROJECT_ID}_cloudbuild/logs'
    paths: ['cloudbuild-log.txt']

notifications:
  - filter: build.status == Build.Status.SUCCESS || build.status == Build.Status.FAILURE
    smtpNotification:
      server: ${_SMTP_SERVER}
      port: ${_SMTP_PORT}
      sender: ${_SMTP_USERNAME}
      from: ${_SMTP_USERNAME}
      recipients:
        - jckail13@gmail.com
      password:
        secretRef: smtp-password
