version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - ./frontend/dist:/app/frontend/dist
      - ./images:/app/images
    environment:
      - PYTHONPATH=/app
      - FLASK_APP=${FLASK_APP}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - VITE_API_URL=${VITE_API_URL}
      - PRODUCTION_URL=${PRODUCTION_URL}
      - RESUME_FILE=${RESUME_FILE}
      - VITE_RESUME_FILE=${VITE_RESUME_FILE}
      - PORT=${PORT}
