import hashlib
import logging
from pathlib import Path

from fastapi import APIRouter, HTTPException, Request, Response
from fastapi.responses import FileResponse
from pydantic import BaseModel

from ..models.data_loader import load_aboutme
from .content import etag_matches

router = APIRouter()
logger = logging.getLogger(__name__)

ASSETS_DIR = Path(__file__).parent.parent.parent / "assets"
DOWNLOAD_NAME = "jordankail_resume.pdf"
# The PDF is regenerated by hand between deploys and the viewer must never
# show a stale copy. "no-cache" lets a cache keep the file but forces it to
# revalidate on every use; the ETag and Last-Modified FileResponse sends make
# that a body-less 304 when the file is unchanged.
REVALIDATE_HEADERS = {"Cache-Control": "no-cache"}


class ResumeFileName(BaseModel):
    resumeFileName: str


def get_resume_file_path() -> Path:
    """Path of the resume named in aboutme.json; 404 if the file is missing."""
    file_name = load_aboutme().resume_name
    if not file_name:
        logger.error("resume_name not found in aboutme data")
        raise HTTPException(status_code=500, detail="Unable to load resume")

    file_path = ASSETS_DIR / file_name
    if not file_path.is_file():
        logger.error("Resume file %r not found", file_name)
        raise HTTPException(status_code=404, detail="Resume not found")
    return file_path


@router.api_route("/resume", methods=["GET", "HEAD"], response_class=FileResponse)
async def serve_resume(request: Request) -> Response:
    """Serve the resume PDF inline, or as an attachment with ``?download``."""
    is_download = "download" in request.query_params
    path = get_resume_file_path()
    # The same validator Starlette derives from the file, checked here because
    # FileResponse sends it but never answers a conditional request itself.
    stat = path.stat()
    etag = '"' + hashlib.md5(f"{stat.st_mtime}-{stat.st_size}".encode(), usedforsecurity=False).hexdigest() + '"'
    if etag_matches(request.headers.get("if-none-match", ""), etag):
        return Response(status_code=304, headers={**REVALIDATE_HEADERS, "ETag": etag})
    return FileResponse(
        path,
        media_type="application/pdf",
        headers={**REVALIDATE_HEADERS, "ETag": etag},
        filename=DOWNLOAD_NAME,
        content_disposition_type="attachment" if is_download else "inline",
    )


@router.get("/resume_file_name", response_model=ResumeFileName)
async def resume_file_name() -> ResumeFileName:
    """Return the resume file name if the file exists."""
    return ResumeFileName(resumeFileName=get_resume_file_path().name)
